app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /en


home:
    path: /
    controller: AppBundle\Controller\HomeController:showAction
    defaults:
        path: /{%locale%}/
        controller: AppBundle:Home:show
        permanent: true


homepage:
    path: /{_locale}/
    controller: AppBundle\Controller\HomeController:showAction
    requirements:
        _locale: en|fr|de|ru
    defaults:
        path: /{_locale}/
        controller: AppBundle:Home:show
        permanent: true
        requirements:
            _locale: en|fr|de|ru




#Category
show_category:
    path: /{_locale}/categories/
    controller: AppBundle\Controller\ProductCategoryController:showAction
    requirements:
        _locale: en|fr|de|ru

create_category:
    path: /{_locale}/categories/create
    controller: AppBundle\Controller\ProductCategoryController:createAction
    requirements:
        _locale: en|fr|de|ru

edit_category:
    path: /{_locale}/categories/edit/{id}
    controller: AppBundle\Controller\ProductCategoryController:updateAction
    requirements:
        _locale: en|fr|de|ru

delete_category:
    path: /{_locale}/categories/delete/{id}
    controller: AppBundle\Controller\ProductCategoryController:deleteAction
    requirements:
        _locale: en|fr|de|ru



#Product
show_products:
    path: /{_locale}/products/
    controller: AppBundle\Controller\ProductsController:showAction
    requirements:
        _locale: en|fr|de|ru

create_product:
    path: /{_locale}/products/create
    controller: AppBundle\Controller\ProductsController:createAction
    requirements:
        _locale: en|fr|de|ru

edit_products:
    path: /{_locale}/products/update/{id}
    controller: AppBundle\Controller\ProductsController:editAction
    requirements:
        _locale: en|fr|de|ru

delete_products:
    path: /{_locale}/products/delete/{id}
    controller: AppBundle\Controller\ProductsController:deleteAction
    requirements:
        _locale: en|fr|de|ru



#Count
count_cost:
    path: /{_locale}/count-cost
    controller: AppBundle\Controller\CountController:indexAction
    requirements:
        _locale: en|fr|de|ru


