app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /en

user_logout:
    path: /logout

#Admin ---------------------------------------------------------------------
admin_page:
    path: /{_locale}/admin
    controller: AppBundle\Controller\Admin\IndexController:indexAction
    requirements:
        _locale: en|fr|de|ru

count_cost:
    path: /{_locale}/admin/count-cost
    controller: AppBundle\Controller\Admin\CountController:indexAction
    requirements:
        _locale: en|fr|de|ru

#PRODUCTS
show_admin_products:
    path: /{_locale}/admin/products
    controller: AppBundle\Controller\Admin\ProductsController:showAction
    requirements:
        _locale: en|fr|de|ru

create_product:
    path: /{_locale}/admin/products/create
    controller: AppBundle\Controller\Admin\ProductsController:createAction
    requirements:
        _locale: en|fr|de|ru

edit_product:
    path: /{_locale}/admin/products/update/{id}
    controller: AppBundle\Controller\Admin\ProductsController:editAction
    requirements:
        _locale: en|fr|de|ru

delete_product:
    path: /{_locale}/admin/products/delete/{id}
    controller: AppBundle\Controller\Admin\ProductsController:deleteAction
    requirements:
        _locale: en|fr|de|ru

#CATEGORY
show_admin_category:
    path: /{_locale}/admin/categories
    controller: AppBundle\Controller\Admin\ProductCategoryController:showAction
    requirements:
        _locale: en|fr|de|ru

create_category:
    path: /{_locale}/admin/categories/create
    controller: AppBundle\Controller\Admin\ProductCategoryController:createAction
    requirements:
        _locale: en|fr|de|ru

edit_category:
    path: /{_locale}/admin/categories/edit/{id}
    controller: AppBundle\Controller\Admin\ProductCategoryController:updateAction
    requirements:
        _locale: en|fr|de|ru

delete_category:
    path: /{_locale}/admin/categories/delete/{id}
    controller: AppBundle\Controller\Admin\ProductCategoryController:deleteAction
    requirements:
        _locale: en|fr|de|ru





#END ADMIN -------------------------------------------------------------------

login:
    path:     /login
    controller: AppBundle:Security:login


#Registaration
register:
    path: /{_locale}/register
    controller: AppBundle\Controller\RegistrationController:registerAction
    requirements:
        _locale: en|fr|de|ru

#Home
home:
    path: /
    controller: AppBundle\Controller\HomeController:showAction
    defaults:
        path: /{%locale%}/
        controller: AppBundle:Home:show
        permanent: true


homepage:
    path: /{_locale}
    controller: AppBundle\Controller\HomeController:showAction
    requirements:
        _locale: en|fr|de|ru
    defaults:
        path: /{_locale}/
        controller: AppBundle:Home:show
        permanent: true
        requirements:
            _locale: en|fr|de|ru


#Category
show_category:
    path: /{_locale}/categories
    controller: AppBundle\Controller\ProductCategoryController:showAction
    requirements:
        _locale: en|fr|de|ru

#Product
show_products:
    path: /{_locale}/products
    controller: AppBundle\Controller\ProductsController:showAction
    requirements:
        _locale: en|fr|de|ru




