security:

    role_hierarchy:
        ROLE_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_USER: ROLE_USER

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_provider:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                provider: user_provider
            logout:
                path: /logout
                target: /


    access_control:
        # потребовать ROLE_ADMIN для /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/.*/products/create, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/.*/products/edit, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/.*/products/delete, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/.*/categories/create, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/.*/categories/edit, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/.*/categories/delete, roles: [ROLE_ADMIN, ROLE_USER] }
        - { path: ^/.*/count-cost, roles: [ROLE_ADMIN] }

