AppBundle\Entity\Product:
  properties:
    name:
    - NotBlank: { message: 'app.product.name.not_blank'}

    price:
    - GreaterThan:
        value: 0
        message: 'app.product.price.greater_null'
    - Type:
        type: numeric
        message: 'app.product.price.type_numeric'
    - NotBlank: { message: 'app.product.price.not_blank'}
    - AppBundle\Validator\Constraints\ContainsNotEqual_100: ~

    description:
    - NotBlank: { message: 'app.product.description.not_blank.'}

    category:
    - NotBlank: { message: 'app.product.category.not_blank.'}

AppBundle\Entity\ProductCategory:
  properties:
    name:
      - NotBlank: { message: 'app.category.name.not_blank'}

AppBundle\Entity\User:
  properties:
    username:
      - NotBlank: { message: 'app.user.username.not_blank'}
    email:
      - NotBlank: { message: 'app.user.email.not_blank'}
      - Email: { message: 'app.user.email.inc_email'}
    plainPassword:
      - NotBlank: { message: 'app.user.plaint_pass.not_blank'}
      - Length:
          max: 4096
          min: 6
          minMessage: 'app.user.plain_pass.min_length'
          maxMessage: 'app.user.plain_pass.max_length'

