AppBundle\Entity\Product:
  properties:
    name:
    - NotBlank: { message: 'app.product.name.not_blank'}

    price:
    - GreaterThan:
        value: 0
        message: 'app.product.price.greater_null'
    - Type:
        type: numeric
        message: 'app.product.price.type_numeric'
    - NotBlank: { message: 'app.product.price.not_blank'}

    description:
    - NotBlank: { message: 'Field description must required.'}

    category:
    - NotBlank: { message: 'Field category must be required.'}

AppBundle\Entity\ProductCategory:
  properties:
    name:
      - NotBlank: { message: 'Field name must be required.'}