AppBundle\Entity\Product:
  properties:
    name:
    - NotBlank: { message: 'app.product.name.not_blank'}

    price:
    - GreaterThan:
        value: 0
        message: 'app.product.price.greater_null'
    - Type:
        type: numeric
        message: 'app.product.price.type_numeric'
    - NotBlank: { message: 'app.product.price.not_blank'}
    - AppBundle\Validator\Constraints\ContainsNotEqual_100: ~

    description:
    - NotBlank: { message: 'app.product.description.not_blank.'}

    category:
    - NotBlank: { message: 'app.product.category.not_blank.'}

AppBundle\Entity\ProductCategory:
  properties:
    name:
      - NotBlank: { message: 'app.category.name.not_blank'}